# Site settings
title: Tom Curry Music Therapy
email: tomcurrymusictherapy@gmail.com
description: "Music Therapy"


# Color settings (hex-codes without the leading hash-tag)
color:
  primary-light: '#ffffff'
  links: '#219ab3'

# Footer settings
footer: Tom Curry

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/TomCurryMusic
  - title: instagram
    url: http://instagram.com/TomCurryMusic

# Build settings
markdown: kramdown
permalink: pretty
